### ISSUE TITLE
Can we move this to NodeGUI org ?

### ISSUE THREAD

**Issue by a7ul** [illBeRoy/parcel-plugin-nodegui#1]
Hi @illBeRoy 

Would you like to move this in the official nodegui org and maintain it there ?
This looks very promising and an alternate bundler will be awesome.
I can add you as a maintainer for this project in the nodegui org.

This would also make it easier to find for people looking for it. 

Cheers

**Comment by illBeRoy** [comment]
Sounds like a great idea, I'll make some minor updates to the project and then send you a transfer request.

Also, do you have a discord channel for the project (or any other kind of discussion platform)?

**Comment by a7ul** [comment]
Hi @illBeRoy  
I just created a community on spectrum here few minutes ago.
https://spectrum.chat/nodegui

Feel free to join in.
